---
- name: Check for required variables
  loop:
    - scalelite_secret_key_base
    - scalelite_loadbalancer_secrets
  when: item not in vars
  fail:
    msg: "missing required variable: {{ item }}"

- name: import recording tasks
  import_tasks: recording.yml
  when: scalelite_enable_recordings | bool
  tags: recording

- name: create installation directory
  file:
    path: "{{ scalelite_install_dir }}"
    state: directory

- name: Retrieve bigbluebutton secret keys
  shell: 'bbb-conf --secret | grep -o "Secret:.*$" | grep -o "[^ ]*$"'
  loop: "{{ groups.bbb_servers | map('extract', hostvars, ['ansible_host']) | list }}"
  register: secret_keys
  delegate_to: "{{ item }}"
  when: scalelite_bbb_servers | length == 0

- name: deploy bbb-servers.yml
  template:
    src: bbb-servers.yml.j2
    dest: "{{ scalelite_install_dir }}/bbb-servers.yml"
    mode: '640'
    owner: root
    group: root
  vars:
    serverlist: "{{ secret_keys.results | default({}) }}"
  failed_when:
    - (scalelite_bbb_servers | length == 0 and
      secret_keys.results | map(attribute='stdout') | join ('') == '' and
      not ansible_check_mode)

- name: Generate docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: "{{ scalelite_install_dir }}/docker-compose.yml"
    mode: '640'
    owner: root
    group: root

- name: Launch docker-compose
  community.docker.docker_compose:
    pull: true
    project_src: "{{ scalelite_install_dir }}"
  when: not ansible_check_mode

- name: sync bbb-servers with scalelite
  become: true
  ansible.builtin.shell: >-
    docker exec -i scalelite-api
    ./bin/rake servers:sync[-,{{ scalelite_sync_method }}] < bbb-servers.yml
  args:
    chdir: "{{ scalelite_install_dir }}"
  tags: scalelite-sync-servers
